# Generated by Django 3.2.7 on 2021-12-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TryOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paket_try_out', models.CharField(max_length=30)),
                ('file_soal', models.FileField(upload_to='')),
                ('durasi_pengerjaan', models.IntegerField()),
            ],
        ),
    ]
