# Generated by Django 4.0 on 2021-12-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rumpun', to='authapp.jurusan')),
            ],
        ),
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, default='', max_length=50)),
                ('materi', models.TextField(blank=True, default='')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('jawaban_benar', models.CharField(max_length=1)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal', to='materi.materi')),
            ],
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapel', to='materi.mapel')),
            ],
        ),
        migrations.AddField(
            model_name='materi',
            name='modul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modul', to='materi.modul'),
        ),
        migrations.CreateModel(
            name='HasilKuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=0)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasilkuis', to='materi.materi')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siswa', to='authapp.student')),
            ],
        ),
    ]
