# Generated by Django 3.2.7 on 2021-12-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soal',
            name='A',
        ),
        migrations.RemoveField(
            model_name='soal',
            name='B',
        ),
        migrations.RemoveField(
            model_name='soal',
            name='C',
        ),
        migrations.RemoveField(
            model_name='soal',
            name='D',
        ),
        migrations.RemoveField(
            model_name='soal',
            name='E',
        ),
        migrations.AddField(
            model_name='soal',
            name='jawaban',
            field=models.JSONField(default=''),
        ),
    ]
