# Generated by Django 3.2.7 on 2021-12-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='A',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='soal',
            name='B',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='soal',
            name='C',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='soal',
            name='D',
            field=models.TextField(default=''),
        ),
    ]
