# Generated by Django 3.2.7 on 2021-11-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='E',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='materi',
            name='judul',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='soal',
            name='A',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='soal',
            name='B',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='soal',
            name='C',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='soal',
            name='D',
            field=models.TextField(default=''),
        ),
    ]
