# Generated by Django 3.2.7 on 2021-12-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materi',
            old_name='Modul',
            new_name='modul',
        ),
        migrations.RenameField(
            model_name='modul',
            old_name='Mapel',
            new_name='mapel',
        ),
    ]
