# Generated by Django 3.2.7 on 2021-12-04 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('materi', '0002_auto_20211204_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilKuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(default=0, max_length=3)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasilkuis', to='materi.materi')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siswa', to='authapp.student')),
            ],
        ),
    ]
