# Generated by Django 3.2.7 on 2021-11-29 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0002_auto_20211129_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='soal_materi',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='soal',
            name='materi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal', to='materi.materi'),
        ),
    ]
