# Generated by Django 3.2.7 on 2021-11-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0003_auto_20211129_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materi',
            name='soal_materi',
        ),
    ]
