# Generated by Django 3.2.7 on 2021-12-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0003_hasilkuis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasilkuis',
            name='nilai',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soal',
            name='jawaban',
            field=models.JSONField(),
        ),
    ]
