# Generated by Django 3.2.7 on 2021-12-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0005_hasilkuis_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasilkuis',
            name='answer',
            field=models.JSONField(default=dict),
        ),
    ]
